---
- name: Poorten Windows
  hosts: win-RDPantheon.DOEKOE.LOCAL
  
  
  tasks: 
  - name: Firewall rule to allow SMTP on TCP port 25
    windows.win_firewall_rule:
      name: SMTP
      localport: 39
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes