---
- name: ANSIBLE - Filebeat installation and configuration 
  hosts: test-ansible
  become: yes
  

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
  
  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes
    
  
  - name: APT - Add elastic.co key
    apt_key: url="https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    when: ansible_distribution == "Ubuntu"
    

  - name: APT - Add elastic.co repository
    apt_repository: repo="deb https://artifacts.elastic.co/packages/7.x/apt stable main" filename="elastic-7.x" update_cache=yes
    when: ansible_distribution == "Ubuntu"
    
  
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
  
  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes
    
  
  - name: FILEBEAT - Install Filebeat
    apt: pkg=filebeat
    when: ansible_distribution == "Ubuntu"
    
 
  #- name: FILEBEAT - Copy base filebeat config  file
  #  copy: src=/srv/ansible/setup-files/filebeat/filebeat.yml dest=/etc/filebeat/filebeat.yml
    
  - name: FILEBEAT - Configure Logstash output part 1
    lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: 'output.elascticsearch:'
      line: '#output.elascticsearch:'
      state: present
      backrefs: yes
      
  
  
  - name: FILEBEAT - Configure Logstash output part 2
    blockinfile:
      dest: /etc/filebeat/filebeat.yml
      insertbefore: '#output.logstash:'
      marker: "# {mark} -- Logstash output configured by Ansible"
      block: |
        output.logstash:
          hosts: ["39.0.0.27:5044"]
          

  - name: FILEBEAT - Restart filebeat
    service: name=filebeat state=restarted