---
- name: Maak VM
  hosts: win-volibear.DOEKOE.LOCAL
  tasks:
    - name: VM
      win_shell: / 
        New-VM -Name Win10VMAnsible -MemoryStartupBytes 4GB -BootDevice VHD -NewVHDPath .\VMs\Win10TestAnsible.vhdx -Path .\VMData -NewVHDSizeBytes 20GB -Generation 1 -Switch Intern-1