---

- name: Interface Vyos
  connection: network_cli
  hosts: all
  tasks:

    - name: configure console logging
      vyos.vyos.vyos_logging:
         dest: console
         facility: all
         level: crit