---

- name: Interface Vyos
  connection: network_cli
  hosts: all
  tasks:

    - name: configuring Vyos interfaces through Ansible
      vyos.vyos.vyos_interfaces:
         config:
         - name: eth2
           description: eth2 Configured by Ansible Module
           speed: auto
           duplex: auto
           enabled: yes