---
- name: Windows updater
  hosts: all
  
  
  tasks:
  - name: Install all security, critical, and rollup updates without a scheduled task
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        - log_path: G:\ansible_Updates.txt
        - state: installed
        - reboot: yes